title: Desktop rack user guide
description: Uživatelská příručka k modelu stolního racku.
theme: just-the-docs

url: "https://rack.martinjagos.eu"

permalink: pretty

aux_links:
  View on Printables: https://www.printables.com/model/1246254-desktop-10-rack

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

back_to_top: true
back_to_top_text: "Back to top"